config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
   before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].nil?
      @flats = Flat.all
    else
      sql_query = "name LIKE :query OR address LIKE :query"
      @flats = Flat.where(sql_query, query: "%#{params[:query]}%")
    end
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save

    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.input :image_url %>
  <%= f.button :submit, class:"btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<div class="row">
  <div class="col-6 m-auto">
    <div class="flat-form">
      <h1>Edit <%= @flat.name %></h1>
      <div class="mt-3">
        <%= render "form", flat: @flat %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="row">
  <div class="col-12">
    <h1>All our Flats</h1>
  </div>
</div>

<div class="row">
  <div class="col">
    <% if @flats.count > 1 %>
      <p>All <%= @flats.count %> flats.</p>
    <% else %>
      <p><%= @flats.count %> flat.</p>
    <% end %>
  </div>
</div>

<div class="row">

  <% @flats.each do |flat| %>
  <% flat_image = flat.image_url || "https://source.unsplash.com/random/?#{rand(0..99)}" %>
    <div class="col-4">
      <div class="flat-card">
        <div class="flat-card-image" style="background-image: url(<%= "'#{flat_image}'" %>)"></div>
        <div class="flat-card-content">
          <div class="flat-card-title">
            <h4><%= flat.name %></h4>
          </div>
          <p><%= flat.address %></p>
          <div class="flex">
            <div class="flex">
              <i class="material-icons mr-2">people</i><span><%= flat.number_of_guests %></span>
            </div>
            <div class="flex ml-3">
              <i class="material-icons mr-2">euro_symbol</i> <%= flat.price_per_night %>
            </div>
          </div>
        </div>
        <div class="flat-card-actions">
          <%= link_to 'More info', flat_path(flat) %>
          <%= link_to 'Edit', edit_flat_path(flat), class:"ml-3 text-warning"%>
          <%= link_to 'Remove', flat_path(flat),
                                method: :delete,
                                data: { confirm: "Are you sure?" },
                                class:"ml-3 text-danger" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="row">
  <div class="col-6 m-auto">
    <div class="flat-form">
      <h1>Add a new Flat</h1>
      <div class="mt-3">
        <%= simple_form_for @flat do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :description %>
          <%= f.input :price_per_night %>
          <%= f.input :number_of_guests %>
          <%= f.button :submit, class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<% flat_image = @flat.image_url || "https://source.unsplash.com/random/?home"%>

<div class="map" style="background-image: url(<%= "'#{flat_image}'" %>)"></div>

<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
        <div class="map" style="background-image: url('')"></div>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>

        <form action="">
          <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">From </span>
            <input type="text" class="form-control" placeholder="20/02/2020" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mt-2">
            <span class="input-group-addon" id="basic-addon1">To </span>
            <input type="text" class="form-control" placeholder="30/03/2020" aria-label="Username" aria-describedby="basic-addon1">
          </div>
          <input type="submit" value="Book" class="btn btn-success mt-2" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="flex">
          <div class="flex">
            <i class="material-icons mr-2">people</i><span><%= @flat.number_of_guests %></span>
          </div>
          <div class="flex ml-3">
            <i class="material-icons mr-2">euro_symbol</i> <%= @flat.price_per_night %>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <div class="flex-align">
          <h6 class="no-mb">Share</h6>

          <div class="flex">
            <i class="fab fa-facebook-square fa-2x mr-2"></i>
            <i class="fab fa-twitter-square fa-2x mr-2"></i>
            <i class="fab fa-pinterest-square fa-2x mr-2"></i>
            <i class="fas fa-envelope-square fa-2x"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Simple Airbnb', flats_path, class:"navbar-brand" %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto flex">
          <%= form_tag flats_path, method: :get, class:"form-inline my-2 my-lg-0" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control mr-sm-2",
              placeholder: "Find a flat"
            %>
            <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
          <% end %>
          <%= link_to 'Add Flat', new_flat_path, class:"btn btn-outline-primary my-2 my-sm-0 ml-2" %>
        </div>
      </div>
    </nav>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>